# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91ef1e87de240246c782239dcb4d548fdea24716161cafefdb2dfb292ffbe16bd6fdc2672ce391eb6dc2eb924e55a0e69add673dc176aad84e8fb0e22ea39931

test:
  secret_key_base: fd88b8ca34d7714bc7bbe285f1bb89af5bc7b76ba16e8b00f462f05d4bfc7cf719a25b1204d7bc1a8794c240ecfd2617b8099c0c1f6d17198c1e4f6d4dda3d77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
